namespace: persistence-core-1-devnet

resources:
  - service.yaml
  - configmap.yaml
  - genesis.yaml
  - validator.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: test-addresses-core
    files:
      - configs/keys.json
      - configs/validators.json
